name: Deploy AlertaPeru360

on:
  push:
    branches: [main] # rama main

jobs:
  deploy-alertaperu360:
    runs-on: ubuntu-latest # github usara una mauina virtual en un entorno Ubuntu para ejecutar los pasos

    steps:
      - name: Clonar repositorio de mi projecto AlertaPeru360
        uses: actions/checkout@v3

      - name: Publicar carpeta /public dentro de gitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # -> 
